/// Generic Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_REGULAR = 12.0;
const TEXT_REGULAR_X = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_SMALL = 10.0;
const TEXT_BIG = 32.0;

const BORDER_WIDTH_SMALL = 1.0;
const PROFILE_IMAGE_SIZE = 40.0;

/// App Specific
const BOOK_IMAGE_WIDTH = 250.0;
const BOOK_LIST_HEIGHT = 740.0;
const BOOK_LIST_ITEM_HEIGHT = 240.0;
const BOOK_LIST_ITEM_WIDTH = 130.0;
const AUDIO_BOOK_LIST_ITEM_WIDTH = 190.0;

const BOOK_IMAGE_HEIGHT_FOR_HOME = 180.0;
const BOOK_IMAGE_HEIGHT_FOR_SMALL_GRID = 200.0;
const BOOK_IMAGE_HEIGHT_FOR_LARGE_GRID = 265.0;

const CHIP_LIST_VIEW_HEIGHT = 55.0;
const CHIP_LIST_ITEM_HEIGHT = 36.0;

const SHEIVES_IMAGE_HEIGHT = 80.0;
const CREATE_NEW_BUTTON_WIDTH = 130.0;

const SHOW_MODAL_LARGE_HEIGHT = 75.0;

const BOOK_IMAGE_HEIGHT_FOR_SEARCH = 100.0;