// Hive Types
const int HIVE_TYPE_ID_BOOK_DETAIL_VO = 1;
const int HIVE_TYPE_ID_BOOK_LIST_RESULT_VO = 2;
const int HIVE_TYPE_ID_BOOK_OVERVIEW_LIST_VO = 3;
const int HIVE_TYPE_ID_BOOK_OVERVIEW_RESULT_VO = 4;
const int HIVE_TYPE_ID_BOOK_SEARCH_ITEMS_VO = 5;
const int HIVE_TYPE_ID_BOOKS_VO = 6;
const int HIVE_TYPE_ID_BUY_LINKS_VO = 7;
const int HIVE_TYPE_ID_IMAGE_LINK_VO = 8;
const int HIVE_TYPE_ID_ISBN_VO = 9;
const int HIVE_TYPE_ID_REVIEWS_VO = 10;
const int HIVE_TYPE_ID_VOLUME_INFO_VO = 11;

// Box Names
const String BOX_NAME_BOOK_OVERVIEW_LIST_VO = "BOX_NAME_BOOK_OVERVIEW_LIST_VO";
const String BOX_NAME_BOOK_LIST_RESULT_VO = "BOX_NAME_BOOK_LIST_RESULT_VO";
const String BOX_NAME_BOOK_SEARCH_ITEMS_VO = "BOX_NAME_BOOK_SEARCH_ITEMS_VO";
const String BOX_NAME_BOOK_LIST_SAVE_TO_HIVE_VO = "BOX_NAME_BOOK_LIST_SAVE_TO_HIVE_VO";